---
# tasks file for tomcatonubuntu
- include_tasks: installjava.yml
- include_tasks: usergroup.yml
- include_tasks: download.yml
- include_tasks: extract.yml
- include_tasks: permission.yml
- include_tasks: configfile.yml
- include_tasks: tomstart.yml 
- include_tasks: tomuser.yml
- include_tasks: tomrestart.yml
- include_tasks: deployjava.yml
- include_tasks: tomrestart.yml

