---
# tasks file for tomcatonubuntu
- include_tasks: installjava.yml
- include_tasks: UserGroup.yml
- include_tasks: download.yml
- include_tasks: extract.yml
- include_tasks: Permission.yml
- include_tasks: configfile.yml
- include_tasks: tomstart.yml