---
- name: chgrp
  file:
    path: /opt/tomcat
    state: directory
    recurse: yes
    group: tomcat

- name: chmod -R g+r conf
  file:
    path: /opt/tomcat/conf
    state: directory
    recurse: yes
    mode: g+r
    group: tomcat

- name: chmod g+x conf
  file:
    path: /opt/tomcat/conf
    state: directory
    mode: g+x
    group: tomcat


- name: chown -R tomcat webapps/
  file: 
    path: /opt/tomcat/webapps/
    state: directory
    recurse: yes
    owner: tomcat

- name: chown -R tomcat work/
  file: 
    path: /opt/tomcat/work/
    state: directory
    recurse: yes
    owner: tomcat



- name: chown -R tomcat temp/
  file: 
    path: /opt/tomcat/temp/
    state: directory
    recurse: yes
    owner: tomcat



- name: chown -R tomcat logs/
  file: 
    path: /opt/tomcat/logs/
    state: directory
    recurse: yes
    owner: tomcat

